[Fix](cloud) Fix cloud compile err (#56686)
Fix cloud compile err, due to https://github.com/apache/doris/pull/56628
```
/mnt/disk2/doris/apache_doris/cloud/src/recycler/azure_obj_client.h:29:7: error: abstract class is marked 'final' [-Werror,-Wabstract-final-class]
   29 | class AzureObjClient final : public ObjStorageClient {
      |       ^
/mnt/disk2/doris/apache_doris/cloud/src/recycler/obj_storage_client.h:106:35: note: unimplemented pure virtual method 'abort_multipart_upload' in 'AzureObjClient'
  106 |     virtual ObjectStorageResponse abort_multipart_upload(ObjectStoragePathRef path,
      |                                   ^
```