[fix](regression-test) fix non stable case test_unique_table_like (#29643)
test_unique_table.groovy and test_unique_table_like.groovy both use database test_unique_db.

If they run at the same time, we may got the following errors:

java.sql.SQLException: errCode = 2, detailMessage = There are still some transactions in the COMMITTED state waiting to be completed. The database [default_cluster:test_unique_db] cannot be dropped. If you want to forcibly drop(cannot be recovered), please use "DROP database FORCE".

Both Master & Branch2.0 have this problem.