[fix](statistics)Fix auto analyze job appender comparator. (#54029)
The old comparator may overflow when cast long to int, which may cause
the comparator throw an exception of:
java.lang.IllegalArgumentException: Comparison method violates its
general contract!