[Fix](Job)Fix some issues in the Insert job. (#44543)
### What problem does this PR solve?
- The job does not account for tasks in the Canceled state. 
- When a job is canceled, its status is marked as FAILED, and a
NullPointerException (NPE) occurs because resources have already been
released.
```
java.lang.NullPointerException: Cannot invoke "org.apache.doris.qe.ConnectContext.getState()" because "this.ctx" is null
	at org.apache.doris.job.extensions.insert.InsertTask.run(InsertTask.java:200) ~[classes/:?]
	at org.apache.doris.job.task.AbstractTask.runTask(AbstractTask.java:167) ~[classes/:?]
	at org.apache.doris.job.executor.DefaultTaskExecutorHandler.onEvent(DefaultTaskExecutorHandler.java:50) ~[classes/:?]
	at org.apache.doris.job.executor.DefaultTaskExecutorHandler.onEvent(DefaultTaskExecutorHandler.java:33) ~[classes/:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) ~[disruptor-3.4.4.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]15e8716a7ab9">
```

- The RESUME job does not immediately schedule the job.