[opt](hive docker)Exit on creating table failed (#47390)
### What problem does this PR solve?

Problem Summary:

There're some table not found error when querying external hive catalog
in CI, like
[#614159](http://43.132.222.7:8111/buildConfiguration/Doris_External_Regression/614159?buildTab=overview&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandPull+Request+Details=true&expandBuildTestsSection=true&expandBuildChangesSection=true&expandBuildDeploymentsSection=false)
and
[#613945](http://43.132.222.7:8111/buildConfiguration/Doris_External_Regression/613945?buildTab=tests&status=failed&expandedTest=build%3A%28id%3A613945%29%2Cid%3A2000000035).
<img width="782" alt="image"
src="https://github.com/user-attachments/assets/74ce8b6f-3116-4aca-a5a5-3d7f3845a1c9"
/>

The create table script should exit once the sql failed, so we can
easily to see which script failed.

#### Failed scripts

Total 7 ~ 10+ failures, you can search `FAILED: ` in [hive metastore
docker
logs](https://github.com/user-attachments/files/18532083/logs.txt).

1. Create table when hive metastore is not ready , like `student`:
    ```bash
2025-01-24T04:30:01.794131928Z FAILED: SemanticException
org.apache.hadoop.hive.ql.metadata.HiveException:
java.lang.RuntimeException: Unable to instantiate
org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient
    ```
2. HQL grammar wrong, like
`/mnt/scripts/data/regression/crdmm_data/run.sh` :
    ```bash
FAILED: ParseException line 3:12 extraneous input 'crdmm_data' expecting
EOF near '<EOF>'
    ```

3. Error at `msck repair table partition_location_2;`, need `set
hive.msck.path.validation=ignore;`, like
`/mnt/scripts/data/multi_catalog/partition_location_2/run.sh`:
    ```bash
FAILED: Execution Error, return code 1 from
org.apache.hadoop.hive.ql.exec.DDLTask
    ```