[Fix](dictionary) Skip auto refresh dictionary if we know source data is invalid (#50863)
avoid too many warn log like:
```
2025-05-12 21:18:55,390 WARN (mysql-nio-pool-11|212) [StmtExecutor.execute():627] Analyze failed. stmt[290, 18cb1394557f4aeb-b2efd4360e8ee1c5]
org.apache.doris.common.NereidsException: errCode = 2, detailMessage = (10.16.10.2)[INVALID_ARGUMENT]The CIDR has duplicate data in IpAddressDictionary
	at org.apache.doris.qe.StmtExecutor.executeByNereids(StmtExecutor.java:802) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:612) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.queryRetry(StmtExecutor.java:574) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:559) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.executeQuery(ConnectProcessor.java:349) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:249) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:233) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:261) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:444) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = (10.16.10.2)[INVALID_ARGUMENT]The CIDR has duplicate data in IpAddressDictionary
	... 13 more
Caused by: java.lang.RuntimeException: errCode = 2, detailMessage = (10.16.10.2)[INVALID_ARGUMENT]The CIDR has duplicate data in IpAddressDictionary
	at org.apache.doris.dictionary.DictionaryManager.dataLoad(DictionaryManager.java:446) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.nereids.trees.plans.commands.refresh.RefreshDictionaryCommand.run(RefreshDictionaryCommand.java:49) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.qe.StmtExecutor.executeByNereids(StmtExecutor.java:771) ~[doris-fe.jar:1.2-SNAPSHOT]
	... 12 more
```