[fix](iceberg)Fix the failure of creating a table in COS  (#49885)
### What problem does this PR solve?

Problem Summary:

When use JDK17 with cos, if create an iceberg table, an error will
occur:
```
java.lang.IllegalAccessError: class org.apache.hadoop.fs.cosn.buffer.CosNMappedBuffer (in unnamed module @0x4bb33f74) cannot access class sun.nio.ch.FileChannelImpl (in module java.base) because module java.base does not export
sun.nio.ch to unnamed module @0x4bb33f74
```

so, we should add JVM config: `--add-opens
java.base/sun.nio.ch=ALL-UNNAMED`.