[test](inverted index) enhace test_build_index case for quickly finished jobs (#42150)
## Proposed changes

Fix case failure like below
```
Exception in inverted_index_p0/test_build_index.groovy(line 185):

    wait_for_latest_op_on_table_finish(tableName, timeout)

    // BUILD INDEX and expect state is RUNNING
    sql """ BUILD INDEX idx_comment ON ${tableName} """
    def state = wait_for_last_build_index_on_table_running(tableName, timeout)
    if (state != "SKIPPED") {
        def result = sql """ SHOW BUILD INDEX WHERE TableName = "${tableName}" ORDER BY JobId """
        assertEquals(result[result.size()-1][1], tableName)
        assertTrue(result[result.size()-1][3].contains("ADD INDEX"))
        assertEquals(result[result.size()-1][7], "RUNNING")
^^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^^

        // CANCEL BUILD INDEX and expect state is CANCELED
        sql """ CANCEL BUILD INDEX ON ${tableName} (${result[result.size()-1][0]}) """
        result = sql """ SHOW BUILD INDEX WHERE TableName = "${tableName}" ORDER BY JobId """
        assertEquals(result[result.size()-1][1], tableName)
        assertTrue(result[result.size()-1][3].contains("ADD INDEX"))
        assertEquals(result[result.size()-1][7], "CANCELLED")
        assertEquals(result[result.size()-1][8], "user cancelled")

        // BUILD INDEX and expect state is FINISHED

Exception:
org.opentest4j.AssertionFailedError: expected: <FINISHED> but was: <RUNNING>
```