branch-3.0: [fix](regression test) fix case test_simplify_comparison_predicate (#46688)
### What problem does this PR solve?

Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

```
suite('test_simplify_comparison_predicate', 'nonConcurrent') {
    def tbl = 'test_simplify_comparison_predicate_tbl'
    def checkExplain = { expression, resExpression ->
        def checker = { explainString, exception, startTime, endTime ->
            assertNull(exception)
            def foundOutputExprs = false
            def succ = false
            for (def line : explainString.split('\n')) {
                if (foundOutputExprs) {
                    assertTrue(line.contains(resExpression), "'${line}' no contains '${resExpression}'")
^^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^^
                    succ = true
                    break
                }
                if (line.contains('OUTPUT EXPRS:')) {
                    foundOutputExprs = true
                }
            }
            assertTrue(foundOutputExprs)
            assertTrue(succ)
        }

Exception:
org.opentest4j.AssertionFailedError: '    (c_tinyint_null IS NULL AND NULL)[#22]' no contains 'AND[c_tinyint_null IS NULL,NULL]' ==> expected: <true> but was: <false>
  at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
  at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
  at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:210)
  at sun.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
  at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
  at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1586)
  at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:611)
```

### Release note

None

### Check List (For Author)

- Test <!-- At least one of them must be included. -->
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
- [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason <!-- Add your reason?  -->

- Behavior changed:
    - [ ] No.
    - [ ] Yes. <!-- Explain the behavior change -->

- Does this need documentation?
    - [ ] No.
- [ ] Yes. <!-- Add document PR link here. eg:
https://github.com/apache/doris-website/pull/1214 -->

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label <!-- Add branch pick label that this PR
should merge into -->