[log](s3) return detailed error message to the user (#39551)
## Proposed changes

This is a follow-up for #38585.

Previously we pass the under layer s3 exceptions by "caused by" chains.
However, this chain of information is not included when returning result
to the user.

This PR adds the detailed error message in the top layer exception.
So the error can be returned to the user. 

For example:
When s3 layer returns Exceptions like this:

```
org.apache.doris.common.DdlException: errCode = 2, detailMessage = Failed to head object for COS, subKey=1, Error code=UnknownHost, Error message=[qa-build.cos.oss-cn-beijing.myqcloud.com](http://qa-build.cos.oss-cn-beijing.myqcloud.com/)
```

The following string is now returned to the user.

```
Failed to head object for COS, subKey=1, Error code=UnknownHost, Error message=[qa-build.cos.oss-cn-beijing.myqcloud.com](http://qa-build.cos.oss-cn-beijing.myqcloud.com/)
```