branch-3.0: [fix](sql cache) fix prepare statement with sql cache throw NullPointerException #45640 (#45649)
```shell
java.lang.NullPointerException: Cannot read field "originStmt" because the return value of "org.apache.doris.analysis.StatementBase.getOrigStmt()" is null
```