[fix](be-jni-env) Fix java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper". (#52821)
### What problem does this PR solve?

Problem Summary:

In some env, jni will throw
``` 
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper".
```

### Release note

Fix java.lang.StackOverflowError thrown from the
UncaughtExceptionHandler in thread "process reaper" by set
`-Djdk.lang.processReaperUseDefaultStackSize`. Similar with
https://bugs.openjdk.org/browse/JDK-8153057, because we use jni with
other c/c++ lib which use thread-local.
We don't know if turning this on has any side effects at this time, so
provide an option 'jdk_process_reaper_use_default_stack_size' to control
it, defaults is true.