[fix](regression) fix test_primary_key_simple_case (#38798)
## Proposed changes

the case is failed:
```
    assertTrue(result.size() == 7)
    assertTrue(result[6][10] == 25)
^^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception:
java.lang.NullPointerException: Cannot invoke method getAt() on null object
```