[fix](Nereids) Add shapeInfo() override in AggregateFunction to preserve table qualifier in EXPLAIN output (#65264)
### What problem does this PR solve?
some regression case output are not stable, like
query_p0/hint/multi_leading.groovy
```
Exception:
java.lang.IllegalStateException: Check tag 'sql5_2' failed:
Check tag 'sql5_2' failed, line 6, CHAR result mismatch.
Expect cell is: ------NestedLoopJoin[INNER_JOIN](cast(sum(c11) as DOUBLE) > avg(t1.c11) / 20.0)
But real is   : ------NestedLoopJoin[INNER_JOIN](cast(sum(c11) as DOUBLE) > (avg(c11) / 20.0))
```

After this pr, the explain output is fixed to `avg(t1.c11)`