[Fix](nereids) fix create view and alter view using old parser checking (#43263)
Problem:
Creating a view on a table with materialized views (MV) results in an
error: failed to init view stmt. For example, executing the following
SQL:
create view v1 as select * from t1 index t_mv_mv.

Root Cause:
The syntax index t_mv_mv is supported only by the new planner and not by
the old planner. During the view creation process, regardless of whether
the new or old optimizer is used, the process eventually calls the
createView method in Env. In the createView method, the persisted SQL of
the view is parsed using the old optimizer's parser. If the parsing
fails, an error is thrown.
As a result, if the SQL for creating a view includes syntax supported
only by the new optimizer, an error occurs.

Solution:
This PR addresses the issue by removing the parsing check from the
createView method in Env. Instead, the check is moved to the respective
classes responsible for creating views in the new and old optimizers.