[refine](function)Remove member variables from functions.  (#58688)
If a function inherits from IFunction, it should not have any member
variables. Because functions can be shared across multiple threads, any
state that needs to be preserved must be placed in FunctionContext.

```
doris/be/src/vec/functions/simple_function_factory.h:161:27: error: static assertion failed due to requirement 'sizeof(doris::vectorized::FunctionMultiply<doris::vectorized::MultiplyDecimalImpl<doris::TYPE_DECIMAL256, doris::TYPE_DECIMAL128I>>) == sizeof(doris::vectorized::IFunction)': Function must be no member data
  161 |             static_assert(sizeof(Function) == sizeof(IFunction), "Function must be no member data");
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```