[fix](nereids) fix subquery unnest can not found aggregate slot (#51086)
when exists multiple subquery in a query block
```sql
select case
                when t1.k1=1 then (select count(*) from t2 where t1.k2=t2.k2) -- count(*)#7
                when t1.k1=2 then (select count(*) from t3 where t1.k2=t3.k2) -- count(*)#12
                else 0 end as kk
        from t1
        order by kk
```

the aggregate function output maybe bind failed and then throw exception
```
org.apache.doris.nereids.exceptions.AnalysisException: Input slot(s) not in child's output: count(*)#7
```

because we only replace the last aggregate function slot(only replace
the `#12`, but not replace the `#7` ):

this pr fix subquery unnest can not found aggregate slot, introduced by
#39471