[fix](connection) kill connection when meeting Write mysql packet failed error (#36559)
Some time we met error like:
```
2024-06-15 17:26:16,492 WARN (mysql-nio-pool-206|11598) [ConnectProcessor.handleQueryException():420] Process one query failed because IOException:
java.io.IOException: Write mysql packet failed.[write=646624, needToWrite=2097119]
at org.apache.doris.mysql.MysqlChannel.realNetSend(MysqlChannel.java:407) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.mysql.MysqlChannel.flush(MysqlChannel.java:436) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.mysql.MysqlChannel.writeBuffer(MysqlChannel.java:467) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.mysql.MysqlChannel.sendOnePacket(MysqlChannel.java:500) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.StmtExecutor.sendResult(StmtExecutor.java:1747) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:1674) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.StmtExecutor.handleQueryWithRetry(StmtExecutor.java:779) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.StmtExecutor.executeByNereids(StmtExecutor.java:731) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:533) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:512) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.ConnectProcessor.executeQuery(ConnectProcessor.java:307) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:203) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:177) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:205) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:258) ~[doris-fe.jar:1.2-SNAPSHOT]
at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_352-352]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_352-352]
at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_352-352]
```

After that, if user call `connection.close()` in jdbc, it may be
blocked.
And we can still see this connection in `show processlist`.

We should kill this connection because it is already broken.