[fix](compile) Compile failed on arm due to no member named 'fallback' in namespace 'simdjson' (#54308)
Fix compile error on arm:
```
In file included from /opt/doris/be/src/exec/es/es_scroll_parser.cpp:42:
In file included from /opt/doris/be/src/runtime/jsonb_value.h:22:
/opt/doris/be/src/util/jsonb_parser_simd.h:282:24: error: no member named 'fallback' in namespace 'simdjson'
  282 |         case simdjson::fallback::number_type::signed_integer:
      |              ~~~~~~~~~~^
/opt/doris/be/src/util/jsonb_parser_simd.h:283:24: error: no member named 'fallback' in namespace 'simdjson'
  283 |         case simdjson::fallback::number_type::unsigned_integer: {
      |              ~~~~~~~~~~^
/opt/doris/be/src/util/jsonb_parser_simd.h:307:24: error: no member named 'fallback' in namespace 'simdjson'
  307 |         case simdjson::fallback::number_type::big_integer: {
      |              ~~~~~~~~~~^
3 errors generated.
```