[fix](compile) fix compile failed on MacOS due to ambiguous std::abs
be/src/vec/functions/function_string.h:3066:56: error: call to 'abs' is ambiguous
    *(result_data + whole_decimal_str_len - 1) = '0' + std::abs(frac_value % 10);
                                                       ^~~~~~~~
CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include/stdlib.h:132:6: note: candidate function
int      abs(int) __pure2;
         ^
llvm@16/bin/../include/c++/v1/stdlib.h:113:61: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY long abs(long __x) _NOEXCEPT {
                                                            ^
llvm@16/bin/../include/c++/v1/stdlib.h:116:66: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {
                                                                 ^
llvm@16/bin/../include/c++/v1/stdlib.h:122:62: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY float abs(float __lcpp_x) _NOEXCEPT {

llvm@16/bin/../include/c++/v1/stdlib.h:126:63: note: candidate function
_LIBCPP_NODISCARD_EXT inline _LIBCPP_INLINE_VISIBILITY double abs(double __lcpp_x) _NOEXCEPT {
                                                              ^
llvm@16/bin/../include/c++/v1/stdlib.h:131:1: note: candidate function
abs(long double __lcpp_x) _NOEXCEPT {
^