[fix](meta) fix timeout for syncing image when FE scales out (#51120)
Related PR: #26003

Problem Summary:

> If image file is very huge, it maybe occurs http Read timed out when
pulling image from FE Master

```java
java.io.IOException: java.net.SocketTimeoutException: Read timed out
        at org.apache.doris.catalog.Env.getNewImage(Env.java:1664)
        at org.apache.doris.catalog.Env.getClusterIdAndRole(Env.java:1126)
        at org.apache.doris.catalog.Env.initialize(Env.java:884)
        at org.apache.doris.DorisFE.start(DorisFE.java:163)
        at org.apache.doris.DorisFE.main(DorisFE.java:83)
Caused by: java.net.SocketTimeoutException: Read timed out
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun. reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1952)
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.iava:1946)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1516)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at org.apache.doris.master.MetaHelper.getResponse(MetaHelper.java:130)
        at org.apache.doris.master.MetaHelper.getRemoteFile(MetaHelper.java:98)
        at org.apache.doris.catalog.Env.getNewImage(Env.java:1657)
        ... 4 more
```