[fix](regression) fix outfile test case failure (#36592)
## Proposed changes

Issue Number: close #xxx

```
Exception:
java.lang.IllegalStateException: /tmp already exists!
```