[fix](group commit) fix NPE in group commit select backend (#43629)
Problem Summary:
```
2024-11-11 12:00:12,200 WARN (mysql-nio-pool-24123|259) execute Exception. stmt[15559118, 7d88d2401de44f4b-8325fbee3de50791]
java.lang.NullPointerException: Cannot invoke "org.apache.doris.system.Backend.isActive()" because "backend" is null
        at org.apache.doris.load.GroupCommitManager.getCachedBackend(GroupCommitManager.java:305) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.load.GroupCommitManager.selectBackendForCloudGroupCommitInternal(GroupCommitManager.java:251) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.load.GroupCommitManager.selectBackendForGroupCommitInternal(GroupCommitManager.java:239) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.load.GroupCommitManager.selectBackendForGroupCommit(GroupCommitManager.java:203) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.cloud.planner.CloudGroupCommitPlanner.selectBackends(CloudGroupCommitPlanner.java:49) ~[doris-fe.jar:1.2-SNAPSHOT]
```
Co-authored-by: meiyi <meiyi@selectdb.com>