[Fix](p0) Deduplicate table names to avoid cross-suit drops (#60466)
In some python_udf p0 tests, two tables with the same name exist under
the same database, and one was just created when the other was tested
and dropped.

```text
2026-02-02 18:53:05.163 INFO [suite-thread-16] (Suite.groovy:572) - Execute sql: DROP TABLE IF EXISTS test_conditional_module;

...

Exception in pythonudtf_p0/test_pythonudtf_exceptions_module.groovy(line 445):
    
            sql """
            INSERT INTO test_conditional_module VALUES 
            (1, -10),
            (2, 0),
            (3, 50),
            (4, 200),
            (5, NULL);
            """
            
            qt_conditional_process """
    ^^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^^
                SELECT id, tmp.input, tmp.category, tmp.result
                FROM test_conditional_module
                LATERAL VIEW udtf_conditional_process_module(val) tmp AS input, category, result
                ORDER BY id;
            """
            
            // Test 6.2: Yield Control - No Output Case
            sql """ DROP FUNCTION IF EXISTS udtf_filter_yield_module(INT); """
            sql """
            CREATE TABLES FUNCTION udtf_filter_yield_module(INT)
    
Exception:  java.sql.SQLException: errCode = 2, detailMessage = Table [test_conditional_module] does not exist in database [regression_test_pythonudtf_p0].(line 3, pos 17)
```