[fix](temp_table) alive session id set should be thread safe (#55315)
### What problem does this PR solve?

Related PR: ##40680

Problem Summary:

java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "str" is null
at org.apache.thrift.protocol.TBinaryProtocol.writeString(TBinaryProtocol.java:227) ~[libthrift-0.16.0.jar:0.16.0]
at org.apache.doris.thrift.TFrontendReportAliveSessionResult$TFrontendReportAliveSessionResultStandardScheme.write(TFrontendReportAliveSessionResult.java:577) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
at org.apache.doris.thrift.TFrontendReportAliveSessionResult$TFrontendReportAliveSessionResultStandardScheme.write(TFrontendReportAliveSessionResult.java:500) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
at org.apache.doris.thrift.TFrontendReportAliveSessionResult.write(TFrontendReportAliveSessionResult.java:429) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
at org.apache.doris.thrift.FrontendService$getAliveSessions_result$getAliveSessions_resultStandardScheme.write(FrontendService.java:33897) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
at org.apache.doris.thrift.FrontendService$getAliveSessions_result$getAliveSessions_resultStandardScheme.write(FrontendService.java:33859) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
at org.apache.doris.thrift.FrontendService$getAliveSessions_result.write(FrontendService.java:33810) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:58) ~[libthrift-0.16.0.jar:0.16.0]
at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.16.0.jar:0.16.0]
at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:250) ~[libthrift-0.16.0.jar:0.16.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]