[fix](jni)Add hadoop-mapreduce-client-core dependencies (#58217)
```
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.mapred.JobConf
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
W 2025-11-20 18:43:57,798 67719 status.h:439] meet error status: [JNI_ERROR]NoClassDefFoundError: org/apache/hadoop/mapred/JobConf | CAUSED BY: ClassNotFoundException: org.apache.hadoop.mapred.JobConf

```