[fix](iceberg) fix querying iceberg partition table error (#57571)
### What problem does this PR solve?

Problem Summary:

java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by:
java.lang.NullPointerException: Cannot invoke
"java.lang.Long.longValue()" because the return value of
"org.apache.iceberg.StructLike.get(int, java.lang.Class)" is null at
org.apache.doris.datasource.iceberg.IcebergUtils.generateIcebergPartition(IcebergUtils.java:1185)
~[doris-fe.jar:1.2-SNAPSHOT] at
org.apache.doris.datasource.iceberg.IcebergUtils.loadIcebergPartition(IcebergUtils.java:1132)