[feature](profile)Enable merging of incomplete profiles. (#39560)
## Proposed changes

```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at org.apache.doris.common.profile.ExecutionProfile.getPipelineAggregatedProfile(ExecutionProfile.java:142) ~[doris-fe.jar:1.2-SNAPSHOT]
```

In the past, we needed to ensure that profiles were complete before
merging. Now, this allows incomplete profiles to be merged, with missing
profiles being marked in the merged profile.
```
                                -  ProjectionTime:  avg  0ns,  max  0ns,  min  0ns
                                -  RowsProduced:  sum  0,  avg  0,  max  0,  min  0
                                -  WaitForDependency[SORT_OPERATOR_DEPENDENCY]Time:  avg  15min2sec,  max  15min2sec,  min  15min2sec
                  Pipeline  :  3(miss  profile):
                  Pipeline  :  4(instance_num=48):
                      LOCAL_EXCHANGE_SINK_OPERATOR  (PASSTHROUGH)  (id=-14):
                            -  CloseTime:  avg  0ns,  max  0ns,  min  0ns
                            -  ExecTime:  avg  29.410us,  max  43.336us,  min  
```


<!--Describe your changes.-->