[fix](deps) fix NoSuchMethodError: newInstanceFromKeytab when using kerberos (#37296)
Issue:
when connect to a kerberosied hive catalog, doris throw error:
```sql
task_scheduler.cpp:276] Instance ab1535db6ff4d42-9b9ae0e5d0952451 pipeline task 1 failed, reason: failed to init reader for file hdfs://HDFS1012085/usr/hive/warehouse/region/000000_0, err: [IO_ERROR]faield to connect to hdfs hdfs://HDFS1012085: (255), Unknown error 255), reason: NoSuchMethodError: newInstanceFromKeytab
```

Reason:
be/lib has old hadoop jars, e.g. hadoop-common-3.3.4.jar etc, and they
are conflict with new version hadoop jars.
what caused this? Doris is built on a directory which has been used for
multiple times, and this directory contains legacy version hadoop jars.
These legacy jars are downloaded by earlier version of doris, after
that, doris upgrade hadoop jars to 3.3.6 by #29939, but these legacy
jars are not cleaned, when build lastest doris, these legacy jars are
copied to be/lib

<img width="1451" alt="image"
src="https://github.com/apache/doris/assets/28004179/0d007e68-7d73-4344-95da-1714d6048642">