[fix](fe) Fix `removeDroppedMember` use incorrect `nodeName`
```
com.sleepycat.je.rep.MasterStateException: (JE 18.3.12) Cannot remove an active master
    at com.sleepycat.je.rep.util.ReplicationGroupAdmin.checkMember(ReplicationGroupAdmin.java:591)
    at com.sleepycat.je.rep.util.ReplicationGroupAdmin.removeMember(ReplicationGroupAdmin.java:315)
    at org.apache.doris.ha.BDBHA.removeDroppedMember(BDBHA.java:262)
    at org.apache.doris.catalog.Env.removeDroppedFrontends(Env.java:3077)
    at org.apache.doris.catalog.Env.transferToMaster(Env.java:1520)
    at org.apache.doris.catalog.Env.access$1300(Env.java:338)
    at org.apache.doris.catalog.Env$5.runOneCycle(Env.java:2792)
    at org.apache.doris.common.util.Daemon.run(Daemon.java:116)
```

* the bug is introduced by https://github.com/apache/doris/pull/35203