[Fix](Authenticator)defaultAuthenticator not init (#43057)
### What problem does this PR solve?
The `defaultAuthenticator` is not initialized. When a configured
authentication plugin implements the `canDea`l method and returns
`false`, the `defaultAuthenticator` will be used, resulting in a login
failure. The client exception message is `RROR 2013 (HY000): Lost
connection to MySQL server at 'reading authorization packet', system
error: 2`. This issue only affects users who use non-built-in
authentication plugins that implement `canDeal` and return false under
certain circumstances.

https://github.com/apache/doris/pull/40113 introduced this issue
(cherry picked from commit dd0c2d81da52b546cece1af6f836dd4ae22bdf22)