temp branch just for qa test (#54108)
Issue Number: close #xxx

Related PR: #xxx

Problem Summary:

None

- Test <!-- At least one of them must be included. -->
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [ ] No need to test or manual test. Explain why:
- [ ] This is a refactor/code format and no logic has been changed.
        - [ ] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason <!-- Add your reason?  -->

- Behavior changed:
    - [ ] No.
    - [ ] Yes. <!-- Explain the behavior change -->

- Does this need documentation?
    - [ ] No.
- [ ] Yes. <!-- Add document PR link here. eg:
https://github.com/apache/doris-website/pull/1214 -->

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label <!-- Add branch pick label that this PR
should merge into -->

Fix again list partition get partition name npe

Fix persist npe

```
2025-08-05 17:46:21,363 ERROR (replayer|110) [EditLog.loadJournal():1440] replay Operation Type 10, log id: 280
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.ReentrantReadWriteLock.readLock()" because "this.rwLock" is null
        at org.apache.doris.catalog.PartitionInfo.readLock(PartitionInfo.java:121) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.PartitionInfo.getDataProperty(PartitionInfo.java:347) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.replayCreateTable(InternalCatalog.java:1371) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.replayCreateTable(Env.java:4781) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:351) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.replayJournal(Env.java:3121) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env$4.runOneCycle(Env.java:2883) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:119) ~[doris-fe.jar:1.2-SNAPSHOT]
```

fix deadlock

```
"mtmv-task-execute-1-thread-1":
	at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
	- parking to wait for  <0x00007fc4be8f7650> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.2/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@17.0.2/AbstractQueuedSynchronizer.java:1027)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@17.0.2/ReentrantReadWriteLock.java:738)
	at org.apache.doris.common.lock.MonitoredReentrantReadWriteLock$ReadLock.lock(MonitoredReentrantReadWriteLock.java:69)
	at org.apache.doris.catalog.Table.readLock(Table.java:187)
	at org.apache.doris.catalog.OlapTable.getPartitionNames(OlapTable.java:1647)
	at org.apache.doris.catalog.MTMV.addTaskResult(MTMV.java:222)
	at org.apache.doris.alter.Alter.processAlterMTMV(Alter.java:1360)
	at org.apache.doris.catalog.Env.addMTMVTaskResult(Env.java:7417)
	at org.apache.doris.job.extensions.mtmv.MTMVTask.after(MTMVTask.java:564)
	at org.apache.doris.job.extensions.mtmv.MTMVTask.onSuccess(MTMVTask.java:408)
	- locked <0x00007fc4be8f78e0> (a org.apache.doris.job.extensions.mtmv.MTMVTask)
	at org.apache.doris.job.task.AbstractTask.runTask(AbstractTask.java:186)
	at org.apache.doris.job.extensions.mtmv.MTMVTask.runTask(MTMVTask.java:489)
	at org.apache.doris.job.executor.TaskProcessor.runTask(TaskProcessor.java:82)
	at org.apache.doris.job.executor.TaskProcessor.lambda$addTask$0(TaskProcessor.java:48)
	at org.apache.doris.job.executor.TaskProcessor$$Lambda$2627/0x00000008020af4f8.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.2/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.2/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
  ```

fix deadlock mvtask

```
"mysql-nio-pool-29":
	at org.apache.doris.job.extensions.mtmv.MTMVTask.cancel(MTMVTask.java:417)
	- waiting to lock <0x00007f2f7761fc68> (a org.apache.doris.job.extensions.mtmv.MTMVTask)
	at org.apache.doris.job.base.AbstractJob.cancelAllTasks(AbstractJob.java:157)
	at org.apache.doris.job.base.AbstractJob.updateJobStatus(AbstractJob.java:307)
	at org.apache.doris.job.manager.JobManager.dropJobInternal(JobManager.java:196)
	at org.apache.doris.mtmv.MTMVJobManager.dropJob(MTMVJobManager.java:135)
	at org.apache.doris.mtmv.MTMVService.dropJob(MTMVService.java:220)
	at org.apache.doris.datasource.InternalCatalog.unprotectDropTable(InternalCatalog.java:1020)
	at org.apache.doris.datasource.InternalCatalog.dropTableInternal(InternalCatalog.java:977)
	at org.apache.doris.datasource.InternalCatalog.dropTable(InternalCatalog.java:937)
	at org.apache.doris.catalog.Env.dropTable(Env.java:4820)
	at org.apache.doris.catalog.Env.dropTable(Env.java:4804)
	at org.apache.doris.nereids.trees.plans.commands.DropMTMVCommand.run(DropMTMVCommand.java:44)
	at org.apache.doris.qe.StmtExecutor.executeByNereids(StmtExecutor.java:704)
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:542)
	at org.apache.doris.qe.StmtExecutor.queryRetry(StmtExecutor.java:504)
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:489)
	at org.apache.doris.qe.ConnectProcessor.executeQuery(ConnectProcessor.java:349)
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:249)
	at org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:233)
	at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:261)
	at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:443)
	at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52)
	at org.apache.doris.mysql.ReadListener$$Lambda$1479/0x0000000801ba5360.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.2/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.2/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)

  "mtmv-task-execute-1-thread-5":
	at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
	- parking to wait for  <0x00007f2f775b8a00> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.2/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.2/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(java.base@17.0.2/AbstractQueuedSynchronizer.java:1027)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(java.base@17.0.2/ReentrantReadWriteLock.java:738)
	at org.apache.doris.common.lock.MonitoredReentrantReadWriteLock$ReadLock.lock(MonitoredReentrantReadWriteLock.java:69)
	at org.apache.doris.catalog.Table.readLock(Table.java:187)
	at org.apache.doris.catalog.OlapTable.getPartitionNames(OlapTable.java:1647)
	at org.apache.doris.catalog.MTMV.addTaskResult(MTMV.java:208)
	at org.apache.doris.alter.Alter.processAlterMTMV(Alter.java:1360)
	at org.apache.doris.catalog.Env.addMTMVTaskResult(Env.java:7417)
	at org.apache.doris.job.extensions.mtmv.MTMVTask.after(MTMVTask.java:564)
	at org.apache.doris.job.extensions.mtmv.MTMVTask.onSuccess(MTMVTask.java:408)
	- locked <0x00007f2f7761fc68> (a org.apache.doris.job.extensions.mtmv.MTMVTask)
	at org.apache.doris.job.task.AbstractTask.runTask(AbstractTask.java:186)
	at org.apache.doris.job.extensions.mtmv.MTMVTask.runTask(MTMVTask.java:489)
	at org.apache.doris.job.executor.TaskProcessor.runTask(TaskProcessor.java:82)
	at org.apache.doris.job.executor.TaskProcessor.lambda$addTask$0(TaskProcessor.java:48)
	at org.apache.doris.job.executor.TaskProcessor$$Lambda$2690/0x000000080204d238.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.2/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.2/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
```

Fix concurrent rename database causes table creation and replay failure