Fix persist npe
```
2025-08-05 17:46:21,363 ERROR (replayer|110) [EditLog.loadJournal():1440] replay Operation Type 10, log id: 280
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.locks.ReentrantReadWriteLock.readLock()" because "this.rwLock" is null
        at org.apache.doris.catalog.PartitionInfo.readLock(PartitionInfo.java:121) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.PartitionInfo.getDataProperty(PartitionInfo.java:347) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.datasource.InternalCatalog.replayCreateTable(InternalCatalog.java:1371) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.replayCreateTable(Env.java:4781) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:351) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.replayJournal(Env.java:3121) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env$4.runOneCycle(Env.java:2883) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:119) ~[doris-fe.jar:1.2-SNAPSHOT]
```