[fix](fe) fix TabletStatMgr MetricRepo.GAUGE_MAX_TABLE_SIZE_BYTES npt (#55182)
```
2025-08-21 05:50:38,980 ERROR (tablet stat mgr|23) [Daemon.run():121] daemon thread got exception. name: tablet stat mgr
java.lang.NullPointerException: Cannot invoke "org.apache.doris.metric.GaugeMetricImpl.setValue(Object)" because "org.apache.doris.metric.MetricRepo.GAUGE_MAX_TABLE_SIZE_BYTES" is null
```