[Test](bloom filter) enhance bloom filter test case with retry logic (#42243)
## Proposed changes

Fix case error as below
```
2024-10-18 09:44:27.415 ERROR [suite-thread-2] (ScriptContext.groovy:122) - Run test_bloom_filter_hit_with_renamed_column in /home/ubuntu/regression-test/doris_branch-2.1/NEREIDS_ASAN/p0/regression-test/suites/bloom_filter_p0/test_bloom_filter_hit_with_renamed_column.groovy failed
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
```

```
Exception in bloom_filter_p0/test_bloom_filter_drop_column.groovy(line 43):


    sql """INSERT INTO ${table_name} values ('1', '1')"""

    qt_select """select * from ${table_name} order by a"""

    // drop column c1
    sql """ALTER TABLE ${table_name} DROP COLUMN c1"""
    // show create table
    def res = sql """SHOW CREATE TABLE ${table_name}"""
    assert res[0][1].contains("\"bloom_filter_columns\" = \"\"")
^^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^^

    // add new column c1
    sql """ALTER TABLE ${table_name} ADD COLUMN c1 ARRAY<STRING>"""
    // insert data
    sql """INSERT INTO ${table_name} values ('2', null)"""
    // select data
    qt_select """select * from ${table_name} order by a"""
}

Exception:
Assertion failed:
assert res[0][1].contains("\"bloom_filter_columns\" = \"\"")
       |  |  |   |
       |  |  |   false
       |  |  'CREATE TABLE `test_bloom_filter_drop_column` (\n  `a` varchar(150) NULL\n) ENGINE=OLAP\nDUPLICATE KEY(`a`)\nDISTRIBUTED BY HASH(`a`) BUCKETS 1\nPROPERTIES (\n"replication_allocation" = "tag.location.default: 3",\n"min_load_replica_num" = "-1",\n"bloom_filter_columns" = "c1",\n"is_being_synced" = "false",\n"storage_medium" = "hdd",\n"storage_format" = "V2",\n"inverted_index_storage_format" = "V1",\n"light_schema_change" = "true",\n"disable_auto_compaction" = "false",\n"enable_single_replica_compaction" = "false",\n"group_commit_interval_ms" = "10000",\n"group_commit_data_bytes" = "134217728"\n);'
       |  ['test_bloom_filter_drop_column', 'CREATE TABLE `test_bloom_filter_drop_column` (\n  `a` varchar(150) NULL\n) ENGINE=OLAP\nDUPLICATE KEY(`a`)\nDISTRIBUTED BY HASH(`a`) BUCKETS 1\nPROPERTIES (\n"replication_allocation" = "tag.location.default: 3",\n"min_load_replica_num" = "-1",\n"bloom_filter_columns" = "c1",\n"is_being_synced" = "false",\n"storage_medium" = "hdd",\n"storage_format" = "V2",\n"inverted_index_storage_format" = "V1",\n"light_schema_change" = "true",\n"disable_auto_compaction" = "false",\n"enable_single_replica_compaction" = "false",\n"group_commit_interval_ms" = "10000",\n"group_commit_data_bytes" = "134217728"\n);']
       [['test_bloom_filter_drop_column', 'CREATE TABLE `test_bloom_filter_drop_column` (\n  `a` varchar(150) NULL\n) ENGINE=OLAP\nDUPLICATE KEY(`a`)\nDISTRIBUTED BY HASH(`a`) BUCKETS 1\nPROPERTIES (\n"replication_allocation" = "tag.location.default: 3",\n"min_load_replica_num" = "-1",\n"bloom_filter_columns" = "c1",\n"is_being_synced" = "false",\n"storage_medium" = "hdd",\n"storage_format" = "V2",\n"inverted_index_storage_format" = "V1",\n"light_schema_change" = "true",\n"disable_auto_compaction" = "false",\n"enable_single_replica_compaction" = "false",\n"group_commit_interval_ms" = "10000",\n"group_commit_data_bytes" = "134217728"\n);']]
```