[fix](cloud) Trigger periodic cloud checkpoints through edit log rolls (#66154)
fix the wrong checkPointVersion when enable
cloud_checkpoint_image_stale_threshold_seconds
```
2026-07-24 04:19:43,353 INFO (leaderCheckpointer|165) [Checkpoint.doCheckpoint():119] last checkpoint journal id: 497, create timestamp: 1784863172078. current finalized journal id: 0
2026-07-24 04:19:43,353 INFO (leaderCheckpointer|165) [Checkpoint.doCheckpoint():130] Trigger checkpoint in cloud mode because latest image is expired. latestImageSeq: 497, latestImageCreateTime: 1784863172078
2026-07-24 04:19:43,353 INFO (leaderCheckpointer|165) [Checkpoint.doCheckpoint():155] begin to generate new image: image.0

2026-07-24 04:19:43,394 WARN (leaderCheckpointer|165) [Checkpoint.doCheckpoint():191] Save image failed: checkpoint version should be 0, actual replayed journal id is 497
org.apache.doris.common.CheckpointException: checkpoint version should be 0, actual replayed journal id is 497
	at org.apache.doris.master.Checkpoint.doCheckpoint(Checkpoint.java:166)
	at org.apache.doris.master.Checkpoint.runAfterCatalogReady(Checkpoint.java:91)
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58)
	at org.apache.doris.common.util.Daemon.run(Daemon.java:119)
```