[Fix](Catalog)Ensure preExecutionAuthenticator is properly initialized (#50839)
### What problem does this PR solve?

https://github.com/apache/doris/pull/50623
Optimize the initialization logic of preExecutionAuthenticator and
remove redundant logic from HadoopIcebergCatalog."

This change improves the robustness of the code by guaranteeing that the
required initialization logic is executed, preventing potential null
references or incomplete setup.
fe.log
```
2025-05-13 04:57:21,348 INFO (thrift-server-pool-22|191) [InternalCatalog.createDb():466] createDb dbName = regression_test_external_table_p0_broker_load, id = 1747082008077
2025-05-13 04:57:21,351 WARN (thrift-server-pool-9|191) [FrontendServiceImpl.fetchSchemaTableData():2341] Failed to fetchSchemaTableData
java.lang.RuntimeException: NullPointerException: Cannot invoke "org.apache.doris.common.security.authentication.PreExecutionAuthenticator.execute(java.util.concurrent.Callable)" because the return value of "org.apache.doris.datasource.ExternalCatalog.getPreExecutionAuthenticator()" is null
	at org.apache.doris.datasource.iceberg.IcebergMetadataCache.loadTable(IcebergMetadataCache.java:133) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.datasource.iceberg.IcebergMetadataCache.lambda$new$1(IcebergMetadataCache.java:71) ~[doris-fe.jar:1.2-SNAPSHOT]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:145) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:56) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at org.apache.doris.datasource.iceberg.IcebergMetadataCache.getIcebergTable(IcebergMetadataCache.java:94) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.datasource.iceberg.IcebergMetadataCache.loadSnapshots(IcebergMetadataCache.java:113) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.datasource.iceberg.IcebergMetadataCache.lambda$new$0(IcebergMetadataCache.java:63) ~[doris-fe.jar:1.2-SNAPSHOT]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:145) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:56) ~[hive-catalog-shade-2.1.4.jar:2.1.4]
	at org.apache.doris.datasource.iceberg.IcebergMetadataCache.getSnapshotList(IcebergMetadataCache.java:89) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.tablefunction.MetadataGenerator.icebergMetadataResult(MetadataGenerator.java:349) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.tablefunction.MetadataGenerator.getMetadataTable(MetadataGenerator.java:225) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.service.FrontendServiceImpl.fetchSchemaTableData(FrontendServiceImpl.java:2335) ~[doris-fe.jar:1.2-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.apache.doris.service.FeServer.lambda$start$0(FeServer.java:60) ~[doris-fe.jar:1.2-SNAPSHOT]
	at jdk.proxy3.$Proxy67.fetchSchemaTableData(Unknown Source) ~[?:?]
	at org.apache.doris.thrift.FrontendService$Processor$fetchSchemaTableData.getResult(FrontendService.java:4777) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.doris.thrift.FrontendService$Processor$fetchSchemaTableData.getResult(FrontendService.java:4757) ~[fe-common-1.2-SNAPSHOT.jar:1.2-SNAPSHOT]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.16.0.jar:0.16.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.16.0.jar:0.16.0]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:250) ~[libthrift-0.16.0.jar:0.16.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.doris.common.security.authentication.PreExecutionAuthenticator.execute(java.util.concurrent.Callable)" because the return value of "org.apache.doris.datasource.ExternalCatalog.getPreExecutionAuthenticator()" is null
	at org.apache.doris.datasource.iceberg.IcebergMetadataCache.loadTable(IcebergMetadataCache.java:130) ~[doris-fe.jar:1.2-SNAPSHOT]
	... 38 more
```
be.log
```
W 2025-05-13 04:57:21,496 14827 status.h:451] meet error status: [INTERNAL_ERROR]TStatus: NullPointerException: Cannot invoke "org.apache.doris.common.security.authentication.PreExecutionAuthenticator.execute(java.util.concurrent.Callable)" because the return value of "org.apache.doris.datasource.ExternalCatalog.getPreExecutionAuthenticator()" is null

	0#  doris::Status doris::Status::create<true>(doris::TStatus const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/basic_string.h:658
	1#  doris::vectorized::MetaScanner::_fetch_metadata(doris::TMetaScanRange const&) at /home/zcp/repo_center/doris_master/doris/be/src/common/status.h:517
	2#  doris::vectorized::MetaScanner::open(doris::RuntimeState*) at /home/zcp/repo_center/doris_master/doris/be/src/common/status.h:517
	3#  doris::vectorized::ScannerScheduler::_scanner_scan(std::shared_ptr<doris::vectorized::ScannerContext>, std::shared_ptr<doris::vectorized::ScanTask>) at /home/zcp/repo_center/doris_master/doris/be/src/vec/exec/scan/scanner_scheduler.cpp:0
	4#  std::_Function_handler<void (), doris::vectorized::ScannerScheduler::submit(std::shared_ptr<doris::vectorized::ScannerContext>, std::shared_ptr<doris::vectorized::ScanTask>)::$_1::operator()() const::{lambda()#1}>::_M_invoke(std::_Any_data const&) at /var/local/ldb-toolchain/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/shared_ptr_base.h:1149
	5#  doris::ThreadPool::dispatch_thread() at /home/zcp/repo_center/doris_master/doris/be/src/util/threadpool.cpp:0
	6#  doris::Thread::supervise_thread(void*) at /var/local/ldb-toolchain/bin/../usr/include/pthread.h:563
	7#  ?
	8#  ?
W 2025-05-13 04:57:21,496 14827 meta_scanner.cpp:295] fetch schema table data from master failed, errmsg=[INTERNAL_ERROR]TStatus: NullPointerException: Cannot invoke "org.apache.doris.common.security.authentication.PreExecutionAuthenticator.execute(java.util.concurrent.Callable)" because the return value of "org.apache.doris.datasource.ExternalCatalog.getPreExecutionAuthenticator()" is null

```