[fix](regression-test) alter some cases nonConcurrent to prevent MapRedTask Execution Error (#47762)
### What problem does this PR solve?
Problem Summary:
Some case will report error when run hive sql:
```text
Exception:
java.sql.SQLException: org.apache.hive.service.cli.HiveSQLException: Error while processing statement: FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
  at org.apache.hive.service.cli.operation.Operation.toSQLException(Operation.java:380)
  at org.apache.hive.service.cli.operation.SQLOperation.runQuery(SQLOperation.java:257)
  at org.apache.hive.service.cli.operation.SQLOperation.access$800(SQLOperation.java:91)
  at org.apache.hive.service.cli.operation.SQLOperation$BackgroundWork$1.run(SQLOperation.java:348)
```