[fix](publish) fix publish failed when balance (#35462)
## Proposed changes

When load and do balance, the publish is failed:
```
2024-05-27 11:40:16,082 WARN (PUBLISH_VERSION|32) [PublishVersionDaemon.tryFinishTxn():204] error happens when finish transaction 4358
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because the return value of "java.util.Map.get(Object)" is null
        at org.apache.doris.transaction.DatabaseTransactionMgr.finishCheckQuorumReplicas(DatabaseTransactionMgr.java:1343) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.transaction.DatabaseTransactionMgr.finishTransaction(DatabaseTransactionMgr.java:1106) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.transaction.GlobalTransactionMgr.finishTransaction(GlobalTransactionMgr.java:455) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.transaction.PublishVersionDaemon.tryFinishTxn(PublishVersionDaemon.java:201) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.transaction.PublishVersionDaemon.publishVersion(PublishVersionDaemon.java:95) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.transaction.PublishVersionDaemon.runAfterCatalogReady(PublishVersionDaemon.java:69) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.2-SNAPSHOT]