[fix](doris compose) fix docker py exception (#39976)
```
Exception:
java.lang.Exception: Exit value: 1 != 0, stdout: {
    "code": 1,
    "err": "Traceback (most recent call last):\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/command.py\", line 336, in run\n    cluster = CLUSTER.Cluster.load(args.NAME)\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/cluster.py\", line 656, in load\n    raise Exception(\nException: Failed to load cluster, its directory /tmp/doris/test_coordidator_be_restart not exists.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/dist-packages/requests/adapters.py\", line 633, in send\n    conn = self.get_connection_with_tls_context(\n  File \"/usr/local/lib/python3.10/dist-packages/requests/adapters.py\", line 489, in get_connection_with_tls_context\n    conn = self.poolmanager.connection_from_host(\n  File \"/usr/lib/python3/dist-packages/urllib3/poolmanager.py\", line 245, in connection_from_host\n    return self.connection_from_context(request_context)\n  File \"/usr/lib/python3/dist-packages/urllib3/poolmanager.py\", line 257, in connection_from_context\n    raise URLSchemeUnknown(scheme)\nurllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/docker/api/client.py\", line 214, in _retrieve_server_version\n    return self.version(api_version=False)[\"ApiVersion\"]\n  File \"/usr/lib/python3/dist-packages/docker/api/daemon.py\", line 181, in version\n    return self._result(self._get(url), json=True)\n  File \"/usr/lib/python3/dist-packages/docker/utils/decorators.py\", line 46, in inner\n    return f(self, *args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/docker/api/client.py\", line 237, in _get\n    return self.get(url, **self._set_request_timeout(kwargs))\n  File \"/usr/local/lib/python3.10/dist-packages/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.10/dist-packages/requests/adapters.py\", line 637, in send\n    raise InvalidURL(e, request=request)\nrequests.exceptions.InvalidURL: Not supported URL scheme http+docker\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/doris-compose.py\", line 54, in <module>\n    data = run(args, disable_log, help)\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/doris-compose.py\", line 38, in run\n    result = cmd.run(args)\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/command.py\", line 386, in run\n    cluster = CLUSTER.Cluster.new(args.NAME, args.IMAGE, args.cloud,\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/cluster.py\", line 640, in new\n    subnet = gen_subnet_prefix16()\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/cluster.py\", line 87, in gen_subnet_prefix16\n    used_subnet = utils.get_docker_subnets_prefix16()\n  File \"/home/ubuntu/regression-test/doris_master/NEREIDS_ASAN/p0/docker/runtime/doris-compose/utils.py\", line 226, in get_docker_subnets_prefix16\n    client = docker.from_env()\n  File \"/usr/lib/python3/dist-packages/docker/client.py\", line 96, in from_env\n    return cls(\n  File \"/usr/lib/python3/dist-packages/docker/client.py\", line 45, in __init__\n    self.api = APIClient(*args, **kwargs)\n  File \"/usr/lib/python3/dist-packages/docker/api/client.py\", line 197, in __init__\n    self._version = self._retrieve_server_version()\n  File \"/usr/lib/python3/dist-packages/docker/api/client.py\", line 221, in _retrieve_server_version\n    raise DockerException(\ndocker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker\n"
}
, stderr: /usr/local/lib/python3.10/dist-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "cipher": algorithms.TripleDES,
/usr/local/lib/python3.10/dist-packages/paramiko/transport.py:258: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
  "class": algorithms.TripleDES,
  at org.apache.doris.regression.suite.SuiteCluster.runCmd(SuiteCluster.groovy:603)
```