[fix](meta) do not check replica allocation when replay (#49569)
### What problem does this PR solve?

Problem Summary:

```
2025-03-27 11:35:33,694 ERROR (stateListener|95) [EditLog.loadJournal():1231] Operation Type 142
org.apache.doris.common.DdlException: errCode = 2, detailMessage = Failed to find enough backend for ssd storage medium. When setting dynamic_partition.hot_partition_num>0, the hot partitions will store in ssd. Please check the replication num, replication tag and storage medium.
	at org.apache.doris.common.util.DynamicPartitionUtil.checkReplicaAllocation(DynamicPartitionUtil.java:254) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.common.util.DynamicPartitionUtil.checkDynamicPartition(DynamicPartitionUtil.java:190) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.ColocateTableIndex.replayModifyReplicaAlloc(ColocateTableIndex.java:914) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.ColocateTableIndex.replayModifyReplicaAlloc(ColocateTableIndex.java:655) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env.replayJournal(Env.java:2759) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.Env$JournalObserver.runOneCycle(Env.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [doris-fe.jar:1.2-SNAPSHOT]
```

We should not throw any exception when checking the properties in replay
logic.
This PR skip the checking logic when replay.
But I am not sure how to reproduce this situation, l can just guess that
after user modify the colocation property
of a table, but some properties of backends are changed, then this issue
may happen.
This PR has been tested by user and it can solve the problem.