[FIx](trino-connector) Fix the issue with trino-connector catalog replay during FE restart. (#36247)
## Proposed changes

When FE restarts, the TrinoConnectorExternalCatalog constructor is not
executed, causing `trinoProperties` to be null. This results in an NPE
issue when accessing the catalog.

```
java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableMap.containsKey(Object)" because "this.trinoProperties" is null
        at org.apache.doris.datasource.trinoconnector.TrinoConnectorExternalCatalog.createConnectorServicesProvider(TrinoConnectorExternalCatalog.java:198) ~[classes/:?]
        at org.apache.doris.datasource.trinoconnector.TrinoConnectorExternalCatalog.initLocalObjectsImpl(TrinoConnectorExternalCatalog.java:140) ~[classes/:?]
        at org.apache.doris.datasource.ExternalCatalog.initLocalObjects(ExternalCatalog.java:263) ~[classes/:?]
        at org.apache.doris.datasource.ExternalCatalog.makeSureInitialized(ExternalCatalog.java:227) ~[classes/:?]
        at org.apache.doris.datasource.ExternalCatalog.getDbNames(ExternalCatalog.java:439) ~[classes/:?]
        at org.apache.doris.qe.ShowExecutor.handleShowDb(ShowExecutor.java:910) ~[classes/:?]
        at org.apache.doris.qe.ShowExecutor.execute(ShowExecutor.java:314) ~[classes/:?]
        at org.apache.doris.qe.StmtExecutor.handleShow(StmtExecutor.java:2826) ~[classes/:?]
        at org.apache.doris.qe.StmtExecutor.executeByLegacy(StmtExecutor.java:1018) ~[classes/:?]
```


<!--Describe your changes.-->