[chore](compilation)fix compilation error in BE benchmark. (#59122)
./build.sh --benchmark

```
be/src/vec/runtime/timestamptz_value.h:120:59: error: implicit conversion loses integer precision: 'int' to 'uint16_t' (aka 'unsigned short') [-Werror,-Wimplicit-int-conversion]
  120 |     dt.unchecked_set_time(year, month, day, hour, minute, second, microsecond);
      |        ~~~~~~~~~~~~~~~~~~                                 ^~~~~~
be/src/vec/runtime/timestamptz_value.h:120:51: error: implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char') [-Werror,-Wimplicit-int-conversion]
  120 |     dt.unchecked_set_time(year, month, day, hour, minute, second, microsecond);
      |        ~~~~~~~~~~~~~~~~~~                         ^~~~~~
be/src/vec/runtime/timestamptz_value.h:120:45: error: implicit conversion loses integer precision: 'int' to 'uint8_t' (aka 'unsigned char') [-Werror,-Wimplicit-int-conversion]
  120 |     dt.unchecked_set_time(year, month, day, hour, minute, second, microsecond);
      |        ~~~~~~~~~~~~~~~~~~                   ^~~~
```

We have a make_datetime function that's only used in beut. 
However, we enabled -Wimplicit-int-conversion checks outside of beut
code, which caused this error.

Maybe we should disable -Wimplicit-int-conversion for the benchmark
instead?