[fix](be) Adapt nullable column unnesting to new interface (#66474)
Related PR: conflict between https://github.com/apache/doris/pull/66242
and https://github.com/apache/doris/pull/66031

Problem Summary:

fix be compile:
```text
In file included from ../src/exprs/function/ai/ai_functions.cpp:19:
In file included from ../src/exprs/function/ai/ai_classify.h:20:
../src/exprs/function/ai/ai_functions.h:312:66: error: too few arguments to function call, expected 2, have 0
  312 |             prompt_columns.emplace_back(argument.unnest_nullable().column);
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~ ^
../src/core/block/column_with_type_and_name.h:86:27: note: 'unnest_nullable' declared here
   86 |     ColumnWithTypeAndName unnest_nullable(const NullableColumnInfo& info,
      |                           ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   87 |                                           bool replace_null_data_to_default) const;
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../src/exprs/function/ai/ai_functions.cpp:29:
../src/exprs/function/ai/embed.h:74:56: error: too few arguments to function call, expected 2, have 0
   74 |         ColumnPtr input_column = input.unnest_nullable().column;
      |                                  ~~~~~~~~~~~~~~~~~~~~~ ^
../src/core/block/column_with_type_and_name.h:86:27: note: 'unnest_nullable' declared here
   86 |     ColumnWithTypeAndName unnest_nullable(const NullableColumnInfo& info,
      |                           ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   87 |                                           bool replace_null_data_to_default) const;
      |                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```