[fix](job) fix NullPointerException when replay job (#53768)
### What problem does this PR solve?

introduce by https://github.com/apache/doris/pull/52911

fix NullPointerException when replay job
```
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.cloudCluster" is null
```