[test](move-memtable) fix false positives in sinkv2 injection tests (#44552)
`test_writer_v2_fault_injection` did not assert Exception being thrown,
which caused false positives.
i.e. Code bugged but test passed.

This PR fixed this problem.
Run this test without #44344, it will now report errors as expected. 

```
2024-11-25 17:03:25.463 ERROR [non-concurrent-thread-1] (ScriptContext.groovy:122) - Run test_writer_v2_fault_injection in ./doris/regression-test/suites/fault_injection_p0/test_writer_v2_fault_injection.groovy failed
org.opentest4j.AssertionFailedError: expected Exception 'load timed out before close waiting', actual success ==> expected: <true> but was: <false>
```