[fix](sql cache) fix prepare statement with sql cache throw NullPointerException (#45640)
fix prepare statement with sql cache throw NullPointerException:
```shell
java.lang.NullPointerException: Cannot read field "originStmt" because the return value of "org.apache.doris.analysis.StatementBase.getOrigStmt()" is null
```