[fix][vcg] Fix SystemInfoService cannot be cast to CloudSystemInfoSer… (#55542)
…vice in AuditLogHelper

due to https://github.com/apache/doris/pull/52515, and just master
branch has this bug.
This has been fixed before in 3.0 and 3.1 branches


```
2025-09-01 15:01:04,817 WARN (mysql-nio-pool-0|173) [AuditLogHelper.logAuditLog():89] Failed to write audit log.
java.lang.ClassCastException: class org.apache.doris.system.SystemInfoService cannot be cast to class org.apache.doris.cloud.system.CloudSystemInfoService (org.apache.doris.system.SystemInfoService and org.apache.doris.cloud.system.CloudSys
temInfoService are in unnamed module of loader 'app')
        at org.apache.doris.qe.AuditLogHelper.logAuditLogImpl(AuditLogHelper.java:319) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.AuditLogHelper.logAuditLog(AuditLogHelper.java:87) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.auditAfterExec(ConnectProcessor.java:227) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.executeQuery(ConnectProcessor.java:387) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:249) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.handleQuery(MysqlConnectProcessor.java:233) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.dispatch(MysqlConnectProcessor.java:261) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.qe.MysqlConnectProcessor.processOnce(MysqlConnectProcessor.java:443) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.ReadListener.lambda$handleEvent$0(ReadListener.java:52) ~[doris-fe.jar:1.2-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```