Revert "[regression-test](fix) fix StreamLoadAction bug" (#51626)
Reverts apache/doris#51461

encounter error when running p2 case: "response:
nulljava.lang.OutOfMemoryError: Java heap space"