[fix](regression test) fix unstable test_alter_colocate_group (#37544)
FIX:

```
Exception in alter_p2/test_alter_colocate_group.groovy(line 130):

def checkGroupsReplicaAlloc = { groupName, replicaNum ->
// groupName -> replicaAlloc
def allocMap = [:]
def groups = sql """ show proc "/colocation_group" """
for (def group : groups)

{ allocMap[group[1]] = group[4] }
assertEquals("tag.location.default: ${replicaNum}".toString(), allocMap[groupName])
^^^^^^^^^^^^^^^^^^^^^^^^^ERROR LINE^^^^^^^^^^^^^^^^^^^^^^^^^
}

def checkTableReplicaAlloc = { tableName, hasDynamicPart, replicaNum ->
def result = sql """ show create table ${tableName} """
def createTbl = result[0][1].toString()
assertTrue(createTbl.indexOf("\"replication_allocation\" = \"tag.location.default: ${replicaNum}\"") > 0)
if (hasDynamicPart) {
assertTrue(createTbl.indexOf(
"\"dynamic_partition.replication_allocation\" = \"tag.location.default: ${replicaNum}\"") > 0)
}

Exception:
org.opentest4j.AssertionFailedError: expected: <tag.location.default: 1> but was: <tag.location.default: 3>
```