[Bug](datetype) add PGenericType for varbinary type (#56375)
### What problem does this PR solve?
Problem Summary:
```
java.sql.SQLException: errCode = 2, detailMessage = (172.20.58.162)[INTERNAL_ERROR][E6] Unknown data type: 41
  0#  doris::Exception::Exception(int, std::basic_string_view<char, std::char_traits<char> > const&, bool) at /home/zcp/repo_center/doris_branch-4.0/doris/be/src/common/exception.cpp:0
  1#  doris::Exception::Exception(int, std::basic_string_view<char, std::char_traits<char> > const&) at /usr/local/ldb-toolchain-v0.26/bin/../lib/gcc/x86_64-pc-linux-gnu/15/include/g++-v15/bits/basic_string.h:280
  2#  doris::Exception::Exception<doris::PGenericType_TypeId>(int, std::basic_string_view<char, std::char_traits<char> > const&, doris::PGenericType_TypeId&&) at /usr/local/ldb-toolchain-v0.26/bin/../lib/gcc/x86_64-pc-linux-gnu/15/include/g++-v15/bits/basic_string.h:257
  3#  doris::vectorized::DataTypeFactory::create_data_type(doris::PColumnMeta const&) at /home/zcp/repo_center/doris_branch-4.0/doris/be/src/vec/data_types/data_type_factory.cpp:332
  4#  doris::vectorized::Block::deserialize(doris::PBlock const&) at /home/zcp/repo_center/doris_branch-4.0/doris/be/src/vec/core/block.cpp:0
```

### Release note

None

### Check List (For Author)

- Test <!-- At least one of them must be included. -->
    - [ ] Regression test
    - [ ] Unit Test
    - [ ] Manual test (add detailed scripts or steps below)
    - [x] No need to test or manual test. Explain why:
- [ ] This is a refactor/code format and no logic has been changed.
        - [x] Previous test can cover this change.
        - [ ] No code files have been changed.
        - [ ] Other reason <!-- Add your reason?  -->

- Behavior changed:
    - [x] No.
    - [ ] Yes. <!-- Explain the behavior change -->

- Does this need documentation?
    - [x] No.
- [ ] Yes. <!-- Add document PR link here. eg:
https://github.com/apache/doris-website/pull/1214 -->

### Check List (For Reviewer who merge this PR)

- [ ] Confirm the release note
- [ ] Confirm test cases
- [ ] Confirm document
- [ ] Add branch pick label <!-- Add branch pick label that this PR
should merge into -->