[Test](binlog) Check correctly for show create database (#45472)
```
Exception:
java.lang.IllegalStateException: Check tag 'select' failed:
Check tag 'select' failed, line 1, CHAR result mismatch.
Expect cell is: CREATE DATABASE `test_recover_db`
But real is   : CREATE DATABASE `test_recover_db`\\nPROPERTIES (\\n"binlog.enable" = "true"\\n)
line 1 mismatch
ExpectRow: [test_recover_db, CREATE DATABASE `test_recover_db`]
RealRow  : [test_recover_db, CREATE DATABASE `test_recover_db`
PROPERTIES (
"binlog.enable" = "true"
)]
```