[fix](table) Fix create table and drop partition race (#55007)
Fix
Step 1. create table include partitions, table's partitions has been add
to map (leak table lock), write editlog1
Step 2. drop partition, write editlog2
Setp 3. first replay editlog2, then replay editlog1, editlog1 toSql()
find patition by partitionId, can't find, npe

```
2025-08-15 17:39:48,792 ERROR (replayer|113) [EditLog.loadJournal():1443] replay Operation Type 10, log id: 363
java.lang.NullPointerException: Cannot invoke "org.apache.doris.catalog.Partition.getName()" because "partition" is null
        at org.apache.doris.catalog.ListPartitionInfo.toSql(ListPartitionInfo.java:164) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.getDdlStmt(Env.java:4468) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.getSyncedDdlStmt(Env.java:3575) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.binlog.CreateTableRecord.<init>(CreateTableRecord.java:83) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:357) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.replayJournal(Env.java:3113) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env$4.runOneCycle(Env.java:2875) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:119) ~[doris-fe.jar:1.2-SNAPSHOT]
```

Co-authored-by: Yongqiang YANG <yangyongqiang@selectdb.com>