[fix](coordinator) fix "PStatus: Finished" (#57985)
fix unstable insert exception, introduced by #57739:
```
Exception:
java.sql.SQLException: errCode = 2, detailMessage = (172.16.0.149)[FINISHED]PStatus: Finished
```