[fix](analyzer) fix some fill up missing slot errors and make some error hints happy (#58912)
this PR fix some analyzer bug and make some error hint happy. 

1. fix bug:

a) grouping scalar function throw error
select a,b from t1 group by grouping sets((a,b),(a)) having grouping_id(a,b) in (0,1,3)
exception: grouping scalar function is not allow in LOGICAL_FILTER

b)  sort contains aggregate function throw error
select 1 from t3 order by sum(a);
exception: LOGICAL_SORT can not contains AggregateFunction expression: sum(a)

c) sort contains window function throw error
select 1000 from t3 order by sum(a) over();
exception: LOGICAL_SORT can not contains AggregateFunction expression: sum(a)

d) having no check full group by for some cases
-- it should throw error b not in group by, but it didn't
select 1000 from t having sum(a) > 0 and b > 0;

There are more fix bugs in this PR, mainly for filling missing slots
rule and bind expression rule when the sql contains
project/sort/qualify/having.

For example, for aggregation, some case should be ok if disable full
group by, but doris still throw exception, then this PR fix this too.

2. make error hint happy

for example:
a) 
select c1 from t1 having count(c1) > 10 order by c1;
without this pr exception:  Input slot(s) not in child's output: c1#1 in plan: LogicalProject[114]
with this pr exception: SORT expression 'c' must appear in the GROUP BY clause or be used in an aggregate function.

b) 
select a, grouping(b) from t1 group by cube(a) order by a;
without this pr exception: Column `b` in GROUPING() does not exist in GROUP BY clause. 
with this pr exception:  LOGICAL_REPEAT 's GROUPING function 'Grouping(b)', its argument 'b' must appear in GROUP BY clause.

there are more fix hint, not list all here.