[fix](dynamic partition) fix dynamic partition thread met uncatch exception (#35778)
dynamic partition thread get table's drop clause met an error due to
dynamic_partition.start = -99999999

```
2024-05-23 10:40:32,072 ERROR (DynamicPartitionScheduler|53) [Daemon.run():118] daemon thread got exception. name: DynamicPartitionScheduler
org.apache.doris.nereids.exceptions.AnalysisException: date/datetime literal [+271768-09-11 00:00:00] is invalid
	at org.apache.doris.nereids.trees.expressions.literal.DateLiteral.normalize(DateLiteral.java:202) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.nereids.trees.expressions.literal.DateTimeLiteral.determineScale(DateTimeLiteral.java:107) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.nereids.types.DateTimeV2Type.forTypeFromString(DateTimeV2Type.java:91) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.nereids.trees.expressions.literal.DateTimeV2Literal.<init>(DateTimeV2Literal.java:38) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.PartitionKey.getDateTimeLiteral(PartitionKey.java:120) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.catalog.PartitionKey.createPartitionKey(PartitionKey.java:98) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.clone.DynamicPartitionScheduler.getDropPartitionClause(DynamicPartitionScheduler.java:431) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.clone.DynamicPartitionScheduler.executeDynamicPartition(DynamicPartitionScheduler.java:555) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.clone.DynamicPartitionScheduler.runAfterCatalogReady(DynamicPartitionScheduler.java:641) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) ~[doris-fe.jar:1.2-SNAPSHOT]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT] 
```

BUG:
1. dynamic partition thread not catch
org.apache.doris.nereids.exceptions.AnalysisException;
2. getDropClauses use dynamic_partition.start as the partitions's start.
But it's error, it should should max(dynamic_partition.start,
-dynamic_partition.history_partition_num).

FIX:
1. dynamic partition thread catch
org.apache.doris.nereids.exceptions.AnalysisException;
2. getDropClauses use start = max(dynamic_partition.start,
-dynamic_partition.history_partition_num);
3. When create table (i.e. create dynamic partion first time), if met an
exception, then throw this exception out, then create table will fail,
so user can known this error;