[fix](trino-connector) fix `NoClassDefFoundError` of hudi `Utils` class (#32846)
Due to the change of this PR #32455 , the `trino-connector-scanner` package cannot access the `hudi_scanner` package, so the exception NoclassDeffounderror will appear.

We need to write a separate Utils class.