[fix](cloud) Fix replay default compute group failed throw exception (#43766)
### What problem does this PR solve?

due to #42504, replay thread will check default compute group auth, if
failed will throw exception, lead to fe can't start

```
2024-11-12 06:49:46,432 ERROR (stateListener|14) [EditLog.loadJournal():1248] replay Operation Type 69, log id: 1124
org.apache.doris.cloud.qe.ComputeGroupException: errCode = 2, detailMessage = set default compute group failed, user regression_test_cloud_user2 has no permission to use compute group 'smoke_test_cluster_01', please grant use privilege first , ComputeGroupException: CURRENT_USER_NO_AUTH_TO_USE_COMPUTE_GROUP, you canuse SQL `GRANT USAGE_PRIV ON COMPUTE GROUP {compute_group_name} TO {user}`
        at org.apache.doris.mysql.privilege.UserProperty.checkCloudDefaultCluster(UserProperty.java:398) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.privilege.UserProperty.update(UserProperty.java:263) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.privilege.UserPropertyMgr.updateUserProperty(UserPropertyMgr.java:91) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.privilege.Auth.updateUserPropertyInternal(Auth.java:1084) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.mysql.privilege.Auth.replayUpdateUserProperty(Auth.java:1077) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:505) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.replayJournal(Env.java:2962) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.transferToMaster(Env.java:1552) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env.access$1200(Env.java:345) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.catalog.Env$5.runOneCycle(Env.java:2841) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) ~[doris-fe.jar:1.2-SNAPSHOT]
```

fix:
ignore check default compute group auth when isReplay eq true

Issue Number: close #xxx

Related PR: #42504