[fix](virtual slot) adjust virtual column expression nullable (#55694)
### What problem does this PR solve?

need adjust nullable for expression of the virtual slot

bug introduced by:  #52701 

example as follow:

SQL: 

```sql
        SELECT t1.*, t2.*
        FROM
            tbl_adjust_virtual_slot_nullable_1 AS t1
        LEFT JOIN tbl_adjust_virtual_slot_nullable_2 AS t2
        ON  t1.c_int = t2.c_int
        WHERE
            NOT (
                    day(t2.c_date) IN (1, 3)
                AND
                    day(t2.c_date) IN (2, 3, 3)
                );
```

throw exception:

```
java.sql.SQLException: errCode = 2, detailMessage = (127.0.0.1)[INTERNAL_ERROR]Could not find function dayofmonth, arg c_date return Nullable(TINYINT)
```