[chore](meta) improve error log to eliminate misunderstanding (#44006)
When a get-role-request submitted from an invalid client, log in master
FE for the same error show different IPs, which is confusing, like
below:
```sql
2024-11-15 02:08:13,714 WARN (qtp1588318071-306|224) [MetaService.isFromValidFe():71] request is not from valid FE. client: 10.88.0.1, 9010
2024-11-15 02:08:13,714 WARN (qtp1588318071-306|224) [RestApiExceptionHandler.unexpectedExceptionHandler():61] unexpected exception
org.apache.doris.httpv2.meta.InvalidClientException: invalid client host: 172.16.48.196
        at org.apache.doris.httpv2.meta.MetaService.checkFromValidFe(MetaService.java:81) ~[doris-fe.jar:1.2-SNAPSHOT]
        at org.apache.doris.httpv2.meta.MetaService.role(MetaService.java:192) ~[doris-fe.jar:1.2-SNAPSHOT]
```

Co-authored-by: Dongyang Li <lidongyang@selectdb.com>