[fix](point query) fix point query throw npe (#47409)
fix point query throw npe, introduced by #46879.

sql:
```sql
select 1
```
the exception:
```
java.sql.SQLException: errCode = 2, detailMessage = Cannot invoke "org.apache.doris.nereids.trees.plans.distribute.FragmentIdMapping.valueList()" because the return value of "org.apache.doris.nereids.NereidsPlanner.getDistributedPlans()" is null
```