[fix](compile) compile fail on MacOS because 'bits/types/struct_timespec.h' not found (#39567)
macos compilation in doris/be/src/runtime/fragment_mgr.cpp reports fatal
error: 'bits/types/struct_timespec.h' file not found

Co-authored-by: 宋光璠 <songguangfan@sf.com>