[Fix](thirdparty) fix that BE can not start when use JDK17 (#29570)
An error occurred when starting BE with JDK17

```java
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "process reaper"
```

This error occurs when BE's java code calls Runtime.exec() to fork the child process.
It turned out that Doris was calling the `glog` library in the C++ layer to cause this problem.


The solution comes from: https://github.com/google/glog/issues/975