[fix](ga) try fix clang format action (#40393)
Because distutils was removed in Python 3.12, we get
ModuleNotFoundError: module named 'distutils'
Use 3.10